export default {
    english: {
        language: 'English',
        signIn: 'SIGN IN',
        signUp: 'SIGN UP',
        password: 'Password',
        username: 'Username',
        firstName: 'First Name',
        secondName: 'Second Name',
        changeSignUp: 'Not a member yet ? ',
        changeSignIn: 'Already member ? ',
        continueWithApi: 'Continue with',
        invalidMail: 'Invalid mail',
        mailUsed: 'Mail already used',
        usernameTooShort: 'Username too short',
        usernameTooLong: 'Username too long',
        firstNameTooLong: 'First Name too long',
        secondNameTooLong: 'Second Name too long',
        lowercase: 'Add a lowercase',
        uppercase: 'Add an uppercase',
        number: 'Add a number',
        pwdTooSHort: 'Password too short',
        wrongMail: 'Mail doesn\'t exist',
        wrongPwd: 'Incorrect password',
        mailSend: 'A confirmation mail has been sent to : ',
        forgotPwd: 'Forgot your password ?'

    },
    french: {
        language: 'Français',
        signIn: 'CONNEXION',
        signUp: 'INSCRIPTION',
        password: 'Mot de passe',
        username: 'Pseudo',
        firstName: 'Prénom',
        secondName: 'Nom de famille',
        changeSignUp: 'Pas encore membre ? ',
        changeSignIn: 'Déjà membre ? ',
        continueWithApi: 'Continuer via',
        invalidMail: 'Veuillez entrer un mail valide',
        mailUsed: 'Ce mail est déjà utilisé',
        usernameTooShort: 'Nom d\'utilisateur trop court',
        usernameTooLong: 'Nom d\'utilisateur trop long',
        firstNameTooLong: 'Prénom trop long',
        secondNameTooLong: 'Nom de famille trop long',
        lowercase: 'Ajoutez une minuscule',
        uppercase: 'Ajoutez une majuscule',
        number: 'Ajoutez un chiffre',
        pwdTooSHort: 'Mot de passe trop court',
        wrongMail: 'Ce mail est associé à aucun compte',
        wrongPwd: 'Mot de passe incorrecte',
        mailSend: 'Un mail de confirmation a été envoyé à : ',
        forgotPwd: 'Mot de passe oublié ?'
    }
}